forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'
	
urlpatterns = [
	path('', views.CategoryList.as_view(), name='home'),
	path('create/', views.CategoryCreate.as_view(), name='category_create'),
	path('<int:category_id>/', views.details, name='category_details'),
	path('<int:pk>/update/', views.CategoryUpdate.as_view(), name='category_update'),
	path('<int:pk>/delete/', views.CategoryDelete.as_view(), name='category_delete'),
	path('<int:category_id>/<int:thread_id>/', views.thread_details, name='thread_details'),
	path('<int:category_id>/<int:thread_id>/update/', views.thread_update, name='thread_update'),
	path('<int:category_pk>/<int:pk>/delete/', views.ThreadDelete.as_view(), name='thread_delete'),
	path('<int:category_id>/<int:thread_id>/<int:post_id>/edit/', views.post_update, name='post_update'),
	path('<int:category_pk>/<int:thread_pk>/<int:pk>/delete/', views.PostDelete.as_view(), name='post_delete'),

	
 ]

unit_three_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('forum/', include('forum.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forum/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    album_name = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.album_name} on {self.artist}"
    
    def get_absolute_url(self):
        return reverse("forum:home")


class Thread(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField(max_length=3000)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} \n {self.title}"

class Post(models.Model):
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=3000)
    date = models.DateField(auto_now_add=True)
    upvotes = models.PositiveIntegerField(default=0)
    downvotes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.user.name}'s post under '{self.thread.title}' thread"

forum/forms.py
from django.forms import ModelForm, Textarea
from .models import Category, Thread, Post


class ThreadForm(ModelForm):
  class Meta:
    model = Thread
    fields = ['title', 'text']
    widgets = {
            'text': Textarea(attrs={'class': 'mt-3'}),
        }

class PostForm(ModelForm):
  class Meta:
    model = Post
    fields = ['text']
    widgets = {
            'text': Textarea(attrs={'placeholder': 'Anything to add...?'}),
        }
    labels = {
            'text': '',
        }

forum/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.http import JsonResponse
from django.core import serializers
from django.urls import reverse
from urllib.parse import parse_qs
from .models import Category, Thread, Post
from .forms import ThreadForm, PostForm
import json
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

@login_required
def details(request, category_id):

    category = Category.objects.get(id=category_id)
    thread_form = ThreadForm()

    is_users_category = True if category.user.id == request.user.id else False
    print(category.user.id)
    print(request.user.id)
    print(is_users_category)
    
    if request.method == 'POST':

        form = ThreadForm(request.POST)

        if form.is_valid():

            new_thread = form.save(commit=False)
            new_thread.user = request.user
            new_thread.category = category
            new_thread.save()


    return render(request, 'category_details.html', {
        'category': category,
        'thread_form': thread_form,
        'is_users_category': is_users_category,
    })


class CategoryUpdate(LoginRequiredMixin, UpdateView):
    model = Category
    fields = ['album_name', 'artist']
    

class CategoryCreate(LoginRequiredMixin, CreateView):
    model = Category
    fields = ['album_name', 'artist']

    def form_valid(self, form):

        form.instance.user = self.request.user
        return super().form_valid(form)


class CategoryList(LoginRequiredMixin, ListView):
    model = Category


class CategoryDelete(LoginRequiredMixin, DeleteView):
    model = Category
    success_url = '/forum'

@login_required
def thread_details(request, category_id, thread_id):

    category = Category.objects.get(id=category_id)
    thread = Thread.objects.get(id=thread_id)
    thread_form = ThreadForm()
    post_form = PostForm()
    is_users_thread = True if category.user.id == request.user.id else False

    # will run when ASYNC code is sent
    if request.method == 'POST':

        json_data = None

        # extract data from request

        if request.POST.dict() != {}:

            print(request.POST.dict())

            request_dict = request.POST.dict()
            request_json = json.dumps(request_dict)
            json_data = json.loads(request_json)  

        else:
        
            json_data = json.loads(request.body.decode('utf-8'))

        
        text = json_data.get('text')

        # create form from text data
        form = PostForm({'text': text})

        if form.is_valid():

            # add information save
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.thread = thread
            new_post.save()

            # get new list of posts
            posts = thread.post_set.all()

            # format to send as JSON
            posts_data = []
            for post in posts:
                post_data = {
                'id': post.id,
                'user': post.user.id,
                'username': post.user.username,
                'text': post.text,
                'date': post.date,
                'upvotes': post.upvotes,
                'downvotes': post.downvotes,
                'thread': post.thread.id,
                }
                posts_data.append(post_data)
            
            return JsonResponse({'message': 'Post added successfully', 'posts': posts_data, 'user_id': request.user.id, 'category_id': category.id, 'thread_id': thread.id}, content_type='application/json')

        
        return JsonResponse({'message': 'Post added unsuccessfully'}, content_type='application/json')
        

    return render(request, 'thread_details.html', {
        'category': category,
        'thread': thread,
        'post_form': post_form,
        'thread_form': thread_form,
        'is_users_thread': is_users_thread,
        'user_id': request.user.id,
    })

@login_required
def thread_update(request, category_id, thread_id):


    if request.method == 'POST':

        thread = Thread.objects.get(id=thread_id)
        
        title = request.POST['title']
        text = request.POST['text']

        thread.title = title
        thread.text = text
        thread.save()

        return redirect('forum:thread_details', category_id=category_id, thread_id=thread_id)

class ThreadDelete(LoginRequiredMixin, DeleteView):
    model = Thread
    
    def get_success_url(self):
        category_id = self.object.category.id
        return reverse('forum:category_details', kwargs={'category_id': category_id})

@login_required
def post_update(request, category_id, thread_id, post_id):

    if request.method == 'POST':

        post = Post.objects.get(id=post_id)
        
        text = request.POST['text']

        post.text = text
        post.save()

        return redirect('forum:thread_details', category_id=category_id, thread_id=thread_id)


class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post

    def get_success_url(self):
        category_id = self.object.thread.category.id
        thread_id = self.object.thread.id
        return reverse('forum:thread_details', kwargs={'category_id': category_id, 'thread_id': thread_id})

forum/templates/forum/category_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="w-3/4 m-auto space-y-1 py-2 my-4">
  <h1 class="text-4xl">Delete Discussion</h1>
</div>
  <h4 class="text-2xl">Are you sure you want to delete this discussion!</h4>

  <div class="bg-white w-3/4 m-auto my-4 py-4">
  <p class="text-2xl">{{ object.album_name }}</p>
  <p class="text-xl">by. {{ object.artist }}</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input class="styled-button" type="submit" value="Yes - Delete!">
    <a class="styled-button" href="{% url 'forum:category_details' object.id %}">Cancel</a>
  </form>
</div>
{% endblock %}

forum/templates/forum/category_form.html
{% extends 'forum_base.html' %}

{% block content %}
  <div class="w-3/4 m-auto space-y-1 py-2 my-4">
  {% if object %}
    
    <h1 class="text-4xl">Edit Your Discussion</h1>
  {% else %}
    <h1 class="text-4xl">Add Discussion</h1>
  {% endif %}
</div>

  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <div class="bg-blue-500 flex justify-center w-3/4 m-auto py-6 pt-6 pb-2 my-3">
  <form class="mx-auto" action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->

      {{ form.as_table }}

    </table>
    <input class="styled-button my-3" type="submit" value="Submit!" class="">
  {% if object %}
    <a class="styled-button inline" href={% url 'forum:category_delete' object.id %}>Delete This Discussion<a>
  {% endif %}
</form>
    </div>
  


{% endblock %}

forum/templates/forum/category_list.html
{% extends 'forum_base.html' %}
{% block content %}

<div class="w-3/4 m-auto space-y-1 py-2 my-4">
  <h1 class="text-4xl">Discussion List</h1>
</div>

<div class="bg-white w-3/4 m-auto my-4">

  <div class="p-2">

  {% for category in category_list %}
    <a class="hover:text-blue-500 ease-in-out" href="{% url 'forum:category_details' category.id %}">
      <div>
          <div>
              <h3 class="text-2xl">{{ category.album_name }}</p>
              <p class="text-lg">by. {{ category.artist }}</p>
          </div>
      </div>
    </a>
    <hr class="w-11/12 m-auto">

  {% endfor %}
  </div>

  </div>

{% endblock %}

forum/templates/forum/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="w-3/4 m-auto space-y-1 py-2 my-4">
  <h1 class="text-4xl">Delete Post</h1>
</div>


  <h4 class="text-2xl">Are you sure you want to delete this post!</h4>

  <div class="bg-white w-3/4 m-auto my-4 py-4">
  <p class="text-lg">{{ object.text }}</p>


  <form action="" method="POST">
    {% csrf_token %}
    <input class="styled-button" type="submit" value="Yes - Delete!">
    <a class="styled-button" href="{% url 'forum:thread_details' object.thread.category.id object.thread.id %}">Cancel</a>
  </form>
</div>
{% endblock %}

forum/templates/forum/thread_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="w-3/4 m-auto space-y-1 py-2 my-4">
  <h1 class="text-4xl">Delete Thread</h1>
</div>

  <h4 class="text-2xl">Are you sure you want to delete this thread!</h4>

  <div class="bg-white w-3/4 m-auto my-4 py-4">
  <p class="text-xl">{{ object.title }}</p>
  <p class="text-lg">{{ object.text }}</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input class="styled-button" type="submit" value="Yes - Delete!">
    <a class="styled-button" href="{% url 'forum:thread_details' object.category.id object.id %}">Cancel</a>

  </form>
</div>

{% endblock %}