forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'
	
urlpatterns = [
	path('', views.CategoryList.as_view(), name='home'),
	path('create/', views.CategoryCreate.as_view(), name='category_create'),
	path('<int:category_id>/', views.details, name='category_details'),
	path('<int:pk>/update/', views.CategoryUpdate.as_view(), name='category_update'),
	path('<int:pk>/delete/', views.CategoryDelete.as_view(), name='category_delete'),
	path('<int:category_id>/<int:thread_id>/', views.thread_details, name='thread_details'),
	path('<int:category_id>/<int:thread_id>/update/', views.thread_update, name='thread_update'),
	path('<int:category_pk>/<int:pk>/delete/', views.ThreadDelete.as_view(), name='thread_delete'),
	path('<int:category_id>/<int:thread_id>/<int:post_id>/edit/', views.post_update, name='post_update'),
	path('<int:category_pk>/<int:thread_pk>/<int:pk>/delete/', views.PostDelete.as_view(), name='post_delete'),

	
 ]

main_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
	
urlpatterns = [
	path('', views.home, name='home'),
    path('index/', views.profile_index, name='index'),
    path('about/', views.about, name='about'),
    path('new_album/create/', views.AlbumCreate.as_view(), name='new_album'),
    path('album/<int:album_id>/review/', views.ReviewCreate.as_view(), name='review_form'),
    path('update_album/<int:pk>/update/', views.AlbumUpdate.as_view(), name='album_update'),
    path('delete_album/<int:pk>/delete/', views.AlbumDelete.as_view(), name='album_delete'),
    path('update_review/<int:pk>/update/', views.ReviewUpdate.as_view(), name='review_update'),
    path('delete_review/<int:pk>/delete/', views.ReviewDelete.as_view(), name='review_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('album/<int:pk>/', views.album_detail, name='detail'),
 ]

unit_three_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('forum/', include('forum.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

class Album(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    artist_name = models.CharField(max_length=200)
    album_cover = models.URLField(blank=True)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
      return reverse('album_update', kwargs={'pk': self.id})


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=1000)
    rating = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(10)]
    )
    album = models.ForeignKey(Album, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
      return reverse('review_delete', kwargs={'pk': self.id})

main_app/forms.py
from django import forms
from .models import Review, Album

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text', 'rating']

class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['name', 'artist_name', 'album_cover']

main_app/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django import forms
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Review, Album
from .forms import ReviewForm, AlbumForm
from decouple import config
import boto3
import uuid
import os
from botocore.exceptions import NoCredentialsError


# Create your views here.
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

@login_required
def profile_index(request):
    albums = Album.objects.filter(user=request.user)
    return render(request, 'profile/index.html', {'albums' : albums })

@login_required
def album_detail(request, pk):
    album = Album.objects.get(id=pk)
    reviews = Review.objects.filter(album=album)

    user_has_review = False
    if request.user.is_authenticated:
        user_reviews = reviews.filter(user=request.user)
        if user_reviews.exists():
            user_has_review = True

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            if not user_has_review:
                review = form.save(commit=False)
                review.album = album
                review.user = request.user
                review.save()
                user_has_review = True

    else:
        form = ReviewForm()

    return render(request, 'profile/album_detail.html', {'album': album, 'reviews': reviews, 'form': form, 'user_has_review': user_has_review})




class AlbumCreate(LoginRequiredMixin, CreateView):
    form_class = AlbumForm
    success_url = '/index/'
    template_name = 'main_app/album_form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user

        album = form.save(commit=False)

        if 'album_cover' in self.request.FILES:

            album_cover = self.request.FILES['album_cover']
            aws_access_key_id = config('AWS_ACCESS_KEY_ID')
            aws_secret_access_key = config('AWS_SECRET_ACCESS_KEY')
            s3_bucket = config('S3_BUCKET')
            s3_base_url = config('S3_BASE_URL')
            
            try:
                s3 = boto3.client(
                    's3',
                    aws_access_key_id=aws_access_key_id,
                    aws_secret_access_key=aws_secret_access_key,
                )

                unique_filename = uuid.uuid4().hex[:6] + album_cover.name[album_cover.name.rfind('.'):]

                s3.upload_fileobj(album_cover, s3_bucket, unique_filename)
                album.album_cover = f"{s3_base_url}{s3_bucket}/{unique_filename}"
            except NoCredentialsError:
                print("Credentials not available")

        album.save()
        return super().form_valid(form)

class AlbumUpdate(LoginRequiredMixin, UpdateView):
  model = Album
  fields = ['name', 'artist_name']
  # Get success redirect will use the return function to pass the name of a view
  def get_success_url(self) -> str:
     return reverse('detail', kwargs= dict(pk=self.object.pk))

class AlbumDelete(LoginRequiredMixin, DeleteView):
  model = Album
  success_url = '/index'

class ReviewCreate(LoginRequiredMixin, CreateView):
    model = Review
    form_class = ReviewForm
    template_name = 'main_app/review_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        album_id = self.kwargs['album_id']
        album = Album.objects.get(pk=album_id)
        context['album'] = album
        return context

    def form_valid(self, form):
        album_id = self.kwargs['album_id']
        album = Album.objects.get(pk=album_id)
        review = form.save(commit=False)
        review.album = album
        review.user = self.request.user 
        return super().form_valid(form)

    def get_success_url(self):
        album_id = self.kwargs['album_id']
        return reverse('detail', kwargs={'pk': album_id})
    
class ReviewDelete(LoginRequiredMixin, DeleteView):
    model = Review
    success_url = '/album/{}/'  
    
    def get_success_url(self):
        return self.success_url.format(self.object.album.pk)
    
class ReviewUpdate(LoginRequiredMixin, UpdateView):
    model = Review
    fields = ['text', 'rating']
  
    def get_success_url(self) -> str:
        album_id = self.object.album.pk
        return reverse('detail', kwargs={'pk': album_id})
    

     
def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<div class="mt-8 text-center">
    <h1 class="text-4xl font-bold">About Page</h1>
    <body>
        <h2>Our Vision:</h2>


        <p>SoundCanvas strives to foster an environment that goes beyond a typical online forum. We envision a place where
            every member is encouraged to express themselves freely, share their personal stories intertwined with music, and
            forge connections that last a lifetime. By celebrating the art of albums, we aim to keep the spirit of immersive
            musical journeys alive in an era of quick listens.</p>
    
        <h2>Join Us:</h2>


        <p>Are you ready to embark on this adventure? Whether you're a vinyl collector, a digital explorer, a lyric
            decipherer, or simply someone who loves to lose themselves in the rhythm, SoundCanvas welcomes you with open
            arms. Come, share your favorite albums, exchange tales of how music has shaped your life, and connect with
            kindred spirits who understand the profound impact of a well-crafted album.</p>
    
        <p>Thank you for being a part of our vibrant community.</p>
    
        <p>Sincerely,<br>The SoundCanvas Team</p>
        </body>

 </div>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" type="image/png" href="{% static 'soundcanvas.png' %}">
    <title>SoundCanvas</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Handjet&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}?7">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.16/dist/tailwind.min.css" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body>
    <nav class="bg-blue-500 p-4 handjet-font-header">
        <div class="max-w-7xl mx-auto flex justify-between items-center">
             <a href="{% url 'home' %}">
                <img src="https://i.imgur.com/OwHTdTS.png" class="nav-logo">
            </a> 
            <ul class="nav-list flex space-x-4">
                <li class="nav-item"><a href="{% url 'about' %}">About</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a href="{% url 'index' %}">My Profile</a></li>
                    <li class="nav-item"><a href="{% url 'new_album' %}">New Album</a></li>
                    <li class="nav-item"><a href="{% url 'forum:home' %}">Discussion</a></li>
                    <li class="nav-item"><a href="{% url 'forum:category_create' %}">New Discussion</a></li>
                    <li class="nav-item"><a href="{% url 'logout' %}">Log Out</a></li>
                {% else %}
                    <li class="nav-item"><a href="{% url 'signup' %}">Sign Up</a></li>    
                    <li class="nav-item"><a href="{% url 'login' %}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

     {% block content %}
     {% endblock %}
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="w-full mt-8 mb-8">
    <div class="text-center">
        <h1 class="text-4xl font-bold handjet-font pb-6">SoundCanvas</h1>
        <p class="text-lg mt-4">A safe haven to discuss and bond over your favorite music albums.</p>
    </div>

    <p class="mt-4 text-lg">Sign up or log in to join the discussions and start sharing!</p>

    <div class="flex justify-center mt-4"> 
        <img src="https://i.imgur.com/OwHTdTS.png" alt="Logo" class="logo">
    </div>

    <div class="text-center mt-4 mb-8">
        <a href="{% url 'signup' %}" class="styled-link">Sign Up</a>
        <a href="{% url 'login' %}" class="styled-link ml-4">Log In</a>
    </div>
</div>
{% endblock %}