forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'
	
urlpatterns = [
	path('', views.CategoryList.as_view(), name='home'),
	path('create/', views.CategoryCreate.as_view(), name='category_create'),
	path('<int:category_id>/', views.details, name='category_details'),
	path('<int:pk>/update/', views.CategoryUpdate.as_view(), name='category_update'),
	path('<int:pk>/delete/', views.CategoryDelete.as_view(), name='category_delete'),
	path('<int:category_id>/<int:thread_id>/', views.thread_details, name='thread_details'),
	path('<int:category_id>/<int:thread_id>/update/', views.thread_update, name='thread_update'),
	path('<int:category_pk>/<int:pk>/delete/', views.ThreadDelete.as_view(), name='thread_delete'),
	path('<int:category_id>/<int:thread_id>/<int:post_id>/edit/', views.post_update, name='post_update'),
	path('<int:category_pk>/<int:thread_pk>/<int:pk>/delete/', views.PostDelete.as_view(), name='post_delete'),

	
 ]

unit_three_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('forum/', include('forum.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forum/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    album_name = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.album_name} on {self.artist}"
    
    def get_absolute_url(self):
        return reverse("forum:home")


class Thread(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField(max_length=3000)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} \n {self.title}"

class Post(models.Model):
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=3000)
    date = models.DateField(auto_now_add=True)
    upvotes = models.PositiveIntegerField(default=0)
    downvotes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.user.name}'s post under '{self.thread.title}' thread"

forum/forms.py
from django.forms import ModelForm, Textarea
from .models import Category, Thread, Post


class ThreadForm(ModelForm):
  class Meta:
    model = Thread
    fields = ['title', 'text']
    widgets = {
            'text': Textarea(attrs={'class': 'mt-3'}),
        }

class PostForm(ModelForm):
  class Meta:
    model = Post
    fields = ['text']
    widgets = {
            'text': Textarea(attrs={'placeholder': 'Anything to add...?'}),
        }
    labels = {
            'text': '',
        }

forum/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.http import JsonResponse
from django.core import serializers
from django.urls import reverse
from urllib.parse import parse_qs
from .models import Category, Thread, Post
from .forms import ThreadForm, PostForm
import json
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

@login_required
def details(request, category_id):

    category = Category.objects.get(id=category_id)
    thread_form = ThreadForm()

    is_users_category = True if category.user.id == request.user.id else False
    print(category.user.id)
    print(request.user.id)
    print(is_users_category)
    
    if request.method == 'POST':

        form = ThreadForm(request.POST)

        if form.is_valid():

            new_thread = form.save(commit=False)
            new_thread.user = request.user
            new_thread.category = category
            new_thread.save()


    return render(request, 'category_details.html', {
        'category': category,
        'thread_form': thread_form,
        'is_users_category': is_users_category,
    })


class CategoryUpdate(LoginRequiredMixin, UpdateView):
    model = Category
    fields = ['album_name', 'artist']
    

class CategoryCreate(LoginRequiredMixin, CreateView):
    model = Category
    fields = ['album_name', 'artist']

    def form_valid(self, form):

        form.instance.user = self.request.user
        return super().form_valid(form)


class CategoryList(LoginRequiredMixin, ListView):
    model = Category


class CategoryDelete(LoginRequiredMixin, DeleteView):
    model = Category
    success_url = '/forum'

@login_required
def thread_details(request, category_id, thread_id):

    category = Category.objects.get(id=category_id)
    thread = Thread.objects.get(id=thread_id)
    thread_form = ThreadForm()
    post_form = PostForm()
    is_users_thread = True if category.user.id == request.user.id else False

    # will run when ASYNC code is sent
    if request.method == 'POST':

        json_data = None

        # extract data from request

        if request.POST.dict() != {}:

            print(request.POST.dict())

            request_dict = request.POST.dict()
            request_json = json.dumps(request_dict)
            json_data = json.loads(request_json)  

        else:
        
            json_data = json.loads(request.body.decode('utf-8'))

        
        text = json_data.get('text')

        # create form from text data
        form = PostForm({'text': text})

        if form.is_valid():

            # add information save
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.thread = thread
            new_post.save()

            # get new list of posts
            posts = thread.post_set.all()

            # format to send as JSON
            posts_data = []
            for post in posts:
                post_data = {
                'id': post.id,
                'user': post.user.id,
                'username': post.user.username,
                'text': post.text,
                'date': post.date,
                'upvotes': post.upvotes,
                'downvotes': post.downvotes,
                'thread': post.thread.id,
                }
                posts_data.append(post_data)
            
            return JsonResponse({'message': 'Post added successfully', 'posts': posts_data, 'user_id': request.user.id, 'category_id': category.id, 'thread_id': thread.id}, content_type='application/json')

        
        return JsonResponse({'message': 'Post added unsuccessfully'}, content_type='application/json')
        

    return render(request, 'thread_details.html', {
        'category': category,
        'thread': thread,
        'post_form': post_form,
        'thread_form': thread_form,
        'is_users_thread': is_users_thread,
        'user_id': request.user.id,
    })

@login_required
def thread_update(request, category_id, thread_id):


    if request.method == 'POST':

        thread = Thread.objects.get(id=thread_id)
        
        title = request.POST['title']
        text = request.POST['text']

        thread.title = title
        thread.text = text
        thread.save()

        return redirect('forum:thread_details', category_id=category_id, thread_id=thread_id)

class ThreadDelete(LoginRequiredMixin, DeleteView):
    model = Thread
    
    def get_success_url(self):
        category_id = self.object.category.id
        return reverse('forum:category_details', kwargs={'category_id': category_id})

@login_required
def post_update(request, category_id, thread_id, post_id):

    if request.method == 'POST':

        post = Post.objects.get(id=post_id)
        
        text = request.POST['text']

        post.text = text
        post.save()

        return redirect('forum:thread_details', category_id=category_id, thread_id=thread_id)


class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post

    def get_success_url(self):
        category_id = self.object.thread.category.id
        thread_id = self.object.thread.id
        return reverse('forum:thread_details', kwargs={'category_id': category_id, 'thread_id': thread_id})

forum/templates/category_details.html
{% extends 'forum_base.html' %}
{% block content %}

<div class="w-3/4 m-auto space-y-1 py-2 my-4">
    <h1 class="text-4xl">{{ category.album_name }}<h1>
    <h4 class="text-2xl">{{ category.artist }}<h4>
    {% if is_users_category %}
        <p class="text-gray-400 text-sm inline pr-1">This is your discussion <a href="{% url 'forum:category_update' category.id %}">&#9999;&#65039;<a></p>
    {% endif %}
</div>
<div class="bg-white w-3/4 m-auto my-4">

    <div id="form-div-thread" class="bg-blue-500 text-center pt-6 pb-2 my-3">
    <form action="{% url 'forum:category_details' category.id %}" method="POST">
        {% csrf_token %}
        <!-- Render the inputs -->
        {{ thread_form.as_p }}
        <input class="styled-button" type="submit" value="Create Thread">
      </form>
    </div>

    <h1 class="text-2xl">List of Threads</h1>


    {% if category.thread_set.count %}

        <div class="text-left p-2">

        {% for thread in category.thread_set.all %}
        
            <a href="{% url 'forum:thread_details' category.id thread.id %}">
                <div>
                    <p class="text-gray-600 text-sm inline">{{thread.user.username}}</p>
                    <div class="pl-2 my-0.5 mt-1 hover:text-blue-500">
                    <h2>{{ thread.title }}</h2>
                    <div class="pl-2 my-0.5 mt-1 hover:text-blue-500">
                    <p class="mb-3">{{ thread.text }}</p>
                    </div>
                    </div>
                </div>
            </a>
        <hr class="w-11/12 m-auto">
        {% endfor %}

        </div>

    {% else %}
    
    <h2>No threads yet!</h2>
    <p>Create a new thread!</p>

{% endif %}
</div>


{% endblock %}

forum/templates/details.html
{% extends 'forum_base.html' %}
{% block content %}

<div>
    <h1>{{ category.album_name }}<h1>
    <h4>{{ category.artist }}<h4>
</div>

{% if category.thread_set.count %}

    {% for thread in category.thread_set.all %}
        <a href="{% url 'forum:thread_details' category.id thread.id %}">
            <div>
                <h2>{{ thread.title }}</h2>
                <p>{{ thread.text }}</p>
            </div>
        </a>
    {% endfor %}

{% else %}
    
    <h2>No threads yet!</h2>
    <p>Create a new thread</p>

    <form action="{% url 'forum:category_details' category.id %}" method="POST">
        {% csrf_token %}
        <!-- Render the inputs -->
        {{ thread_form.as_p }}
        <input type="submit" value="Create Thread">
      </form>

{% endif %}

{% endblock %}

forum/templates/forum_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>SoundCanvas</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="icon" type="image/png" href="{% static 'soundcanvas.png' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Handjet&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}?7">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.16/dist/tailwind.min.css" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body>
    <nav class="bg-blue-500 p-4 handjet-font-header">
        <div class="max-w-7xl mx-auto flex justify-between items-center">
             <a href="{% url 'home' %}">
                <img src="https://i.imgur.com/OwHTdTS.png" class="nav-logo">
            </a> 
            <ul class="nav-list flex space-x-4">
                <li class="nav-item"><a href="{% url 'about' %}">About</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a href="{% url 'index' %}">My Profile</a></li>
                    <li class="nav-item"><a href="{% url 'new_album' %}">New Album</a></li>
                    <li class="nav-item"><a href="{% url 'forum:home' %}">Discussion</a></li>
                    <li class="nav-item"><a href="{% url 'forum:category_create' %}">New Discussion</a></li>
                    <li class="nav-item"><a href="{% url 'logout' %}">Log Out</a></li>
                {% else %}
                    <li class="nav-item"><a href="{% url 'signup' %}">Sign Up</a></li>    
                    <li class="nav-item"><a href="{% url 'login' %}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

     {% block content %}
     {% endblock %}
</body>
</html>

forum/templates/thread_details.html
{% extends 'forum_base.html' %}
{% block content %}
{% load static %}



<div class="w-3/4 m-auto space-y-1 py-2 my-4">
    <h1 class="text-4xl">{{ category.album_name }}<h1> 
    <h4 class="text-2xl">{{ category.artist }}<h4>
</div>


<div class="bg-white w-3/4 m-auto my-4">
    <div class="text-left p-2">
        
        <p class="text-gray-700 text-sm inline pr-1">{{category.user.username}}</p>

        {% if is_users_thread %}

        <p class="text-gray-400 text-sm inline pr-1">this is your thread </p>

        <button id="thread_button">&#9999;&#65039;</button>

        {% endif %}

        <div class="pl-2 my-0.5">

            <h1 id="title" class="text-xl">{{ thread.title }}</h1>
            <div class="pl-2 my-0.5">
                <p id="text" class="text-lg">{{ thread.text }}</p>
            </div>
            {% if is_users_thread %}

                {% comment %} form to update thread {% endcomment %}
                <div id="form-div-thread" style="display: none;" class="bg-blue-500 text-center pt-6 pb-2 my-3">
                    <form id="form-thread" action="{% url 'forum:thread_update' category.id thread.id %}" method="POST">
                        {% csrf_token %}

                        <p>
                            <label>Title:</label>
                            <input type="text" name="title" maxlength="200" required id="form_title"></input>
                        </p>
                        <p>
                            <label>Text:</label>
                            <textarea class="mt-3" name="text" cols="40" rows="10" maxlength="3000" id="form_text" required></textarea> 
                        </p>
                        <input class="styled-button" type="submit" value="Update Form">
                    </form>

                    <a class="styled-button" href={% url 'forum:thread_delete' category.id thread.id %}>Delete This Thread</a>
                </div>
            
        {% endif %}
        </div>

    </div>


    {% comment %} form to add post {% endcomment %}
    <div class="bg-blue-500 pt-6 pb-2" id="form-div">
        <form id="form" action="{% url 'forum:thread_details' category.id thread.id %}" method="POST">
            {% csrf_token %}

            {{ post_form.as_p }}
            <input class="styled-button" type="submit" value="Reply">
        </form>
    </div>

    {% if thread.post_set.count %}
    <div id="posts-container" class="!text-left p-2">
        {% for post in thread.post_set.all %}

                <div id="header">
                    <p class="text-gray-700 text-sm inline pr-1">{{post.user.username}}</p>
                    {% if post.user.id == user_id %}
                        <p class="text-gray-400 text-sm inline pr-1">this is your post</p>
                        <button id="edit-post-button">&#9999;&#65039;</button>
                    {% endif %}
                    
                    <div class="pl-2 my-0.5">
                    <h2>{{ post.text }}</h2>

                    {% comment %} form to edit post {% endcomment %}
                    {% if post.user.id == user_id %}


                        <div id="edit-form-post" style="display: none;" class="bg-blue-500 flex justify-center text-center pt-6 pb-2">
                            <form class="text-center" id="form-post" action="{% url 'forum:post_update' category.id thread.id post.id %}" method="POST">
                                {% csrf_token %}
                                <p>
                                    <textarea name="text" cols="40" rows="10" maxlength="3000" id="form_text" required>{{ post.text }}</textarea> 
                                </p>
                                <input class="styled-button" type="submit" value="Update Post">
                            </form>

                            <a class="styled-button" href="{% url 'forum:post_delete' category.id thread.id post.id %}">Delete This Post</a>
                        </div>
                    {% endif %}
                    </div>
                </div>

        {% endfor %}
    </div>
    {% else %}
        
        <div id="posts-container" class="!text-left p-2"></div>
        <h2 id="h2">No posts yet!</h2>
        <p id="p">Create a new post!</p>

    {% endif %}
</div>

<script src="{% static 'js/thread_details.js' %}?3"></script>

{% endblock %}